-- Leader_Images
-- Author: wldcmzy
-- DateCreated: 7/23/2023 9:58:01 AM
--------------------------------------------------------------
INSERT INTO LoadingInfo			
(	LeaderType,				ForegroundImage,						BackgroundImage						)	VALUES
(	'LEADER_RADIANCE',	'IMG_LEADER_RADIANCE_FOREGROUND_.dds',	'IMG_LEADER_RADIANCE_BACKGROUND_.dds'	),
(	'LEADER_GOD_OF_GODS',	'IMG_LEADER_GODOFGOD_FOREGROUND_.dds',	'IMG_LEADER_GODOFGOD_BACKGROUND_.dds'	),
(	'LEADER_WANDERER',	'IMG_LEADER_WANDERER_FOREGROUND_.dds',	'IMG_LEADER_WANDERER_BACKGROUND_.dds'	),
(	'LEADER_WYRMS',		'IMG_LEADER_WYRMS_FOREGROUND_.dds',		'IMG_LEADER_WYRMS_BACKGROUND_.dds'		),
(	'LEADER_GRIMM',		'IMG_LEADER_GRIMM_FOREGROUND_.dds',		'IMG_LEADER_GRIMM_BACKGROUND_.dds'		);

INSERT INTO DiplomacyInfo	
(		Type,							BackgroundImage				)	VALUES
(	'LEADER_RADIANCE',		'IMG_LEADER_RADIANCE_BACKGROUND_.dds'	),
(	'LEADER_GOD_OF_GODS',	'IMG_LEADER_GODOFGOD_BACKGROUND_.dds'	),
(	'LEADER_WANDERER',		'IMG_LEADER_WANDERER_BACKGROUND_.dds'	),
(	'LEADER_WYRMS',			'IMG_LEADER_WYRMS_BACKGROUND_.dds'		),
(	'LEADER_GRIMM',			'IMG_LEADER_GRIMM_BACKGROUND_.dds'		);