-- MomentIllustration
-- Author: wldcmzy
-- DateCreated: 7/23/2023 2:45:11 PM
--------------------------------------------------------------
INSERT INTO MomentIllustrations
(MomentIllustrationType,					MomentDataType,				GameDataType,								Texture													)	VALUES
('MOMENT_ILLUSTRATION_UNIQUE_UNIT',			'MOMENT_DATA_UNIT',			'UNIT_HOLLOW_KNIGHT',						'MOMENT_UNIT_HOLLOW_KNIGHT_.dds'						),
('MOMENT_ILLUSTRATION_UNIQUE_BUILDING',		'MOMENT_DATA_BUILDING',		'BUILDING_TEACHERS_ARCHIVES',				'MOMENT_BUILDING_TEACHERS_ARCHIVES_.dds'				),
('MOMENT_ILLUSTRATION_UNIQUE_BUILDING',		'MOMENT_DATA_BUILDING',		'BUILDING_COLOSSEUM_OF_FOOLS',				'MOMENT_BUILDING_COLOSSEUM_OF_FOOLS_.dds'				),
('MOMENT_ILLUSTRATION_UNIQUE_BUILDING',		'MOMENT_DATA_BUILDING',		'BUILDING_PLEASURE_HOUSE',					'MOMENT_BUILDING_PLEASURE_HOUSE_.dds'					),
('MOMENT_ILLUSTRATION_UNIQUE_BUILDING',		'MOMENT_DATA_BUILDING',		'BUILDING_THE_GRIMM_TROUPE',				'MOMENT_BUILDING_THE_GRIMM_TROUPE_.dds'					),
('MOMENT_ILLUSTRATION_UNIQUE_DISTRICT',		'MOMENT_DATA_DISTRICT',		'DISTRICT_FLOURISHING_CROSSROADS',			'MOMENT_DISTRICT_FLOURISHING_CROSSROADS_.dds'			),
('MOMENT_ILLUSTRATION_UNIQUE_DISTRICT',		'MOMENT_DATA_DISTRICT',		'DISTRICT_PALACE_GROUNDS',					'MOMENT_DISTRICT_PALACE_GROUNDS_.dds'					),
('MOMENT_ILLUSTRATION_UNIQUE_DISTRICT',		'MOMENT_DATA_DISTRICT',		'DISTRICT_TEMPLE_OF_THE_BLACK_EGG_SQUARE',	'MOMENT_DISTRICT_TEMPLE_OF_THE_BLACK_EGG_SQUARE_.dds'	);
