-- HollowNest_Civilization_Trait_Relic
-- Author: wldcmzy
-- DateCreated: 7/24/2023 8:47:19 PM
--------------------------------------------------------------

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_HOLLOWNEST', 'MODIFIER_HOLLOWNEST_RELIC_1'),
('TRAIT_CIVILIZATION_HOLLOWNEST', 'MODIFIER_HOLLOWNEST_RELIC_2'),
('TRAIT_CIVILIZATION_HOLLOWNEST', 'MODIFIER_HOLLOWNEST_RELIC_3');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MODIFIER_HOLLOWNEST_RELIC_1', 'MODIFIER_PLAYER_GRANT_RELIC', 0, 0, 0, NULL, NULL),
('MODIFIER_HOLLOWNEST_RELIC_2', 'MODIFIER_PLAYER_GRANT_RELIC', 0, 0, 0, NULL, NULL),
('MODIFIER_HOLLOWNEST_RELIC_3', 'MODIFIER_PLAYER_GRANT_RELIC', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MODIFIER_HOLLOWNEST_RELIC_1', 'Amount', '1'),
('MODIFIER_HOLLOWNEST_RELIC_2', 'Amount', '1'),
('MODIFIER_HOLLOWNEST_RELIC_3', 'Amount', '1'),
('MODIFIER_HOLLOWNEST_RELIC_1', 'RelicSource', 'RELIC_SOURCE_TRIBAL_VILLAGE'),
('MODIFIER_HOLLOWNEST_RELIC_2', 'RelicSource', 'RELIC_SOURCE_RELIGIOUS_UNIT'),
('MODIFIER_HOLLOWNEST_RELIC_3', 'RelicSource', 'RELIC_SOURCE_GOVERNOR');
